---
title: "Figure 5"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(fig.width = 8, fig.height = 5)

library(tidyverse)
library(nloptr)
library(phyloseq)
library(stringr)
library(RColorBrewer)
library(ggpubr)
library(ggforce)
library(limma)
library(vegan)
library(MASS)
library(pander)
panderOptions('table.caption.prefix', NULL)
panderOptions('table.continues', NULL)
panderOptions('table.emphasize.rownames', FALSE)

source("ancom_bc.R")
source("ancom.R")
```

# 1. Read in OTU table and meta data

```{r, message=FALSE, warning=FALSE, comment=NA}
# Meta data
meta_data=read_tsv("../data/global_gut/global_gut_metadata.txt")
meta_data=meta_data%>%transmute(Sample.ID=`#SampleID`, age=AGE, sex=SEX, country=COUNTRY)%>%
  arrange(Sample.ID)
meta_data=meta_data[complete.cases(meta_data), ]
meta_data$age=as.numeric(meta_data$age)
meta_data$country=recode(meta_data$country, `GAZ:Malawi` = "MA", 
                         `GAZ:United States of America` = "US", `GAZ:Venezuela` = "VEN")

# Taxonomy
taxonomy=read_tsv("../data/global_gut/global_gut_taxonomy.txt")
taxonomy=taxonomy%>%rowwise()%>%
  mutate(genus_name=paste(Phylum, Genus, sep = ";"))

# OTU table
otu_table=read_tsv("../data/global_gut/global_gut_otu.txt")
otu_table=otu_table[, -532]
otu_table$OTU_ID=taxonomy$genus_name[match(otu_table$OTU_ID, taxonomy$OTU_ID)]
otu_table=as.data.frame(otu_table)
otu_table[, -1]=apply(otu_table[, -1], 2, as.numeric)

# Aggregate into genus level
genus_table=otu_table%>%group_by(OTU_ID)%>%
  summarise_all(sum)
non_info_pos=grep("\\g__\\b", genus_table$OTU_ID) # Exact match
genus_table=genus_table[-non_info_pos, ]
genus_table=as.data.frame(genus_table)
```

# 2. Normalization efficacy

**Comparing MA vs VEN.**

```{r, message=FALSE, warning=FALSE, comment=NA, eval=FALSE}
# Subset meta data
meta.data=meta_data%>%filter(country%in%c("MA", "VEN"))
meta.data$country=as.character(meta.data$country)
# Subset OTU table
obs.abn=genus_table
rownames(obs.abn)=obs.abn$OTU_ID
obs.abn=obs.abn[, -1]
obs.abn=obs.abn[, meta.data$Sample.ID]

# Recode sample ID
meta.data$Sample.ID=seq(nrow(meta.data))
colnames(obs.abn)=seq(nrow(meta.data))

feature.table=obs.abn; sample.var="Sample.ID"; group.var="country"; 
zero.cut=0.90; lib.cut=1000; neg.lb=TRUE
pre.process=feature_table_pre_process(feature.table, meta.data, sample.var, 
                                      group.var, zero.cut, lib.cut, neg.lb)
feature.table=pre.process$feature.table
library.size=pre.process$library.size
group.name=pre.process$group.name
group.ind=pre.process$group.ind
struc.zero=pre.process$structure.zeros
```

## 2.1 ANCOM-BC

```{r, message=FALSE, warning=FALSE, comment=NA, eval=FALSE}
# Paras for ANCOM-BC
grp.name=group.name; grp.ind=group.ind; adj.method="BH"
tol.EM=1e-5; max.iterNum=100; perNum=1000; alpha=0.05

# Run ANCOM-BC
out=ANCOM_BC(feature.table, grp.name, grp.ind, struc.zero, adj.method, 
             tol.EM, max.iterNum, perNum, alpha)
ancom.bc=out$d

y.ancom.bc=t(t(log(out$feature.table+1))-ancom.bc)
y.ancom.bc=y.ancom.bc+abs(min(y.ancom.bc, na.rm = T))
dist.ancom.bc=vegdist(t(y.ancom.bc), method="bray", na.rm = T) 
fit.ancom.bc=isoMDS(dist.ancom.bc, k=2)
mds.xy.ancom.bc=data.frame(method = "ANCOM-BC", fit.ancom.bc$points)
mds.xy.ancom.bc$country=meta.data$country[match(colnames(out$feature.table), meta.data$Sample.ID)]
```

## 2.2 ELib-UQ

```{r, message=FALSE, warning=FALSE, comment=NA, eval=FALSE}
countdata=obs.abn
zero.threshold=0.90
taxa.info.ind=apply(countdata, 1, function(x) sum(x==0)/ncol(countdata))
countdata=countdata[which(taxa.info.ind<zero.threshold), ]+1L

groupdata=meta.data$country
dds=edgeR::DGEList(counts = countdata, group = groupdata)
dds=edgeR::calcNormFactors(dds, method="upperquartile")
UQ1=dds$samples$norm.factors*colSums(countdata, na.rm = T)

y.uq1=t(t(log(countdata))-log(UQ1))
y.uq1=y.uq1+abs(min(y.uq1))
dist.uq1=vegdist(t(y.uq1), method="bray", na.rm = T) 
fit.uq1=isoMDS(dist.uq1, k=2)
mds.xy.uq1=data.frame(method = "ELib-UQ", fit.uq1$points, country = meta.data$country)
```

## 2.3 ELib-TMM

```{r, message=FALSE, warning=FALSE, comment=NA, eval=FALSE}
dds=edgeR::DGEList(counts = countdata, group = groupdata)
dds=edgeR::calcNormFactors(dds, method="TMM")
TMM1=dds$samples$norm.factors*colSums(countdata, na.rm = T)

y.tmm1=t(t(log(countdata))-log(TMM1))
y.tmm1=y.tmm1+abs(min(y.tmm1))
dist.tmm1=vegdist(t(y.tmm1), method="bray", na.rm = T) 
fit.tmm1=isoMDS(dist.tmm1, k=2)
mds.xy.tmm1=data.frame(method = "ELib-TMM", fit.tmm1$points, country = meta.data$country)
```

## 2.4 CSS

```{r, message=FALSE, warning=FALSE, comment=NA, eval=FALSE}
rownames(meta.data)=meta.data$Sample.ID
phenotypeData = Biobase::AnnotatedDataFrame(meta.data)
obj = metagenomeSeq::newMRexperiment(countdata, phenoData=phenotypeData, featureData=NULL)
# Calculating normalization factors
obj = metagenomeSeq::cumNorm(obj)
CSS = metagenomeSeq::normFactors(obj)

y.css=t(t(log(countdata))-log(CSS))
y.css=y.css+abs(min(y.css))
dist.css=vegdist(t(y.css), method="bray", na.rm = T) 
fit.css=isoMDS(dist.css, k=2)
mds.xy.css=data.frame(method = "CSS", fit.css$points, country = meta.data$country)
```

## 2.5 MED

```{r, message=FALSE, warning=FALSE, comment=NA, eval=FALSE}
coldata=meta.data
count.table=DESeq2::DESeqDataSetFromMatrix(countData = countdata, 
                                           colData = coldata, design = ~ country)
dds=DESeq2::DESeq(count.table, quiet = TRUE)
MED=DESeq2::sizeFactors(dds)

y.med=t(t(log(countdata))-log(MED))
y.med=y.med+abs(min(y.med))
dist.med=vegdist(t(y.med), method="bray", na.rm = T) 
fit.med=isoMDS(dist.med, k=2)
mds.xy.med=data.frame(method = "MED", fit.med$points, country = meta.data$country)
```

## 2.6 UQ

```{r, message=FALSE, warning=FALSE, comment=NA, eval=FALSE}
groupdata=meta.data$country
dds=edgeR::DGEList(counts = countdata, group = groupdata)
dds=edgeR::calcNormFactors(dds, method="upperquartile")
UQ2=dds$samples$norm.factors

y.uq2=t(t(log(countdata))-log(UQ2))
y.uq2=y.uq2+abs(min(y.uq2))
dist.uq2=vegdist(t(y.uq2), method="bray", na.rm = T) 
fit.uq2=isoMDS(dist.uq2, k=2)
mds.xy.uq2=data.frame(method = "UQ", fit.uq2$points, country = meta.data$country)
```

## 2.7 TMM

```{r, message=FALSE, warning=FALSE, comment=NA, eval=FALSE}
dds=edgeR::DGEList(counts = countdata, group = groupdata)
dds=edgeR::calcNormFactors(dds, method="TMM")
TMM2=dds$samples$norm.factors

y.tmm2=t(t(log(countdata))-log(TMM2))
y.tmm2=y.tmm2+abs(min(y.tmm2))
dist.tmm2=vegdist(t(y.tmm2), method="bray", na.rm = T) 
fit.tmm2=isoMDS(dist.tmm2, k=2)
mds.xy.tmm2=data.frame(method = "TMM", fit.tmm2$points, country = meta.data$country)
```

## 2.8 TSS

```{r, message=FALSE, warning=FALSE, comment=NA, eval=FALSE}
TSS=colSums(countdata, na.rm = T)

y.tss=t(t(log(countdata))-log(TSS))
y.tss=y.tss+abs(min(y.tss))
dist.tss=vegdist(t(y.tss), method="bray", na.rm = T) 
fit.tss=isoMDS(dist.tss, k=2)
mds.xy.tss=data.frame(method = "TSS", fit.tss$points, country = meta.data$country)
```

## 2.7 Between Group Sum of Squares

```{r, message=FALSE, warning=FALSE, comment=NA, eval=FALSE}
ss_compute=function(x){
  x=as.matrix(x)
  ss=sum(t(t(x)-colMeans(x, na.rm = T))^2, na.rm = T)
  return(ss)
}

mds.xy.ancom.bc=mds.xy.ancom.bc%>%mutate(scale_x1=scale(X1), scale_x2=scale(X2))
mds.xy.uq1=mds.xy.uq1%>%mutate(scale_x1=scale(X1), scale_x2=scale(X2))
mds.xy.tmm1=mds.xy.tmm1%>%mutate(scale_x1=scale(X1), scale_x2=scale(X2))
mds.xy.css=mds.xy.css%>%mutate(scale_x1=scale(X1), scale_x2=scale(X2))
mds.xy.med=mds.xy.med%>%mutate(scale_x1=scale(X1), scale_x2=scale(X2))
mds.xy.uq2=mds.xy.uq2%>%mutate(scale_x1=scale(X1), scale_x2=scale(X2))
mds.xy.tmm2=mds.xy.tmm2%>%mutate(scale_x1=scale(X1), scale_x2=scale(X2))
mds.xy.tss=mds.xy.tss%>%mutate(scale_x1=scale(X1), scale_x2=scale(X2))

mds.list=list(mds.xy.ancom.bc, mds.xy.uq1, mds.xy.tmm1, mds.xy.css, 
              mds.xy.med, mds.xy.uq2, mds.xy.tmm2, mds.xy.tss)
bss.df=data.frame(method=c("ANCOM-BC", "ELib-UQ", "ELib-TMM", "CSS", "MED", "UQ", "TMM", "TSS"), bss = NA)
for (i in 1:length(mds.list)) {
  method=mds.list[[i]]
  tss=ss_compute(method%>%dplyr::select(scale_x1, scale_x2))
  wss=ss_compute(method%>%filter(country=="MA")%>%dplyr::select(scale_x1, scale_x2))+
    ss_compute(method%>%filter(country=="VEN")%>%dplyr::select(scale_x1, scale_x2))
  bss=tss-wss
  bss.df[i, "bss"]=bss
}

txt.df = data.frame(X1=0.2, X2=0.25, bss.df)
txt.df$bss = paste0("BSS = ", round(txt.df$bss, 0))
p.df = rbind(mds.xy.ancom.bc, mds.xy.uq1, mds.xy.tmm1, mds.xy.css, 
             mds.xy.med, mds.xy.uq2, mds.xy.tmm2, mds.xy.tss)

write.csv(txt.df, "../data/global_gut/bss.csv", row.names = FALSE)
write.csv(p.df, "../data/global_gut/nmds.csv", row.names = FALSE)
```

# 3. Fig. 5

```{r, message=FALSE, warning=FALSE, comment=NA}
txt.df = read_csv("../data/global_gut/bss.csv")
p.df = read_csv("../data/global_gut/nmds.csv")
txt.df$method = factor(txt.df$method, levels = c("ANCOM-BC", "ELib-UQ", "ELib-TMM", "CSS",
                                                 "MED", "UQ", "TMM", "TSS"))
p.df$method = factor(p.df$method, levels = c("ANCOM-BC", "ELib-UQ", "ELib-TMM", "CSS",
                                             "MED", "UQ", "TMM", "TSS"))
p=ggplot(p.df, aes(X1, X2, color = country)) + geom_point(size = 0.3) + 
  facet_wrap(.~method, nrow = 2)+scale_y_continuous(limits = c(-0.3, 0.3))+
  labs(x="First NMDS coordinate", y="Second NMDS coordinate")+
  scale_color_discrete(name="", breaks=c("MA", "VEN"), labels = c("Malawi", "Venezuela"))+
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom",
        strip.background = element_rect(fill="white"))+
  guides(color = guide_legend(override.aes = list(size=3)))+
  geom_text(data = txt.df, mapping = aes(x = X1, y = X2, label = bss, color = NULL,group= NULL))
p
ggsave("../figures/Figure 5.pdf", width=8, height=5, units='in')
ggsave("../figures/Figure 5.jpeg", width=8, height=5, units='in', dpi = 300)
```

# Session information

```{r, message=FALSE, warning=FALSE, comment=NA}
sessionInfo()
devtools::session_info()
```


